import type { DashboardLocale } from '@/lib/dashboard/content';

type CommonWorkbenchCopy = {
  taskFlow: string;
  generateNow: string;
  uploadImage: string;
  chooseFromLibrary: string;
  loadingLibrary: string;
  noTemplates: string;
  templateCount: (count: number) => string;
  materialCount: (count: number) => string;
  uploadClick: string;
  resultReady: string;
  waitingUpload: string;
  examples: string;
  refresh: string;
  credits: (count: number) => string;
  invalidImage: string;
  imageTooLarge: string;
  uploadPrepareError: string;
  uploadFailed: string;
  imageSaveError: string;
  statusLoadError: string;
  generationStartError: string;
  missingJobError: string;
  queued: string;
  generating: string;
};

export const commonWorkbenchCopy: Record<DashboardLocale, CommonWorkbenchCopy> = {
  pt: {
    taskFlow: 'Fluxo',
    generateNow: 'Gerar agora',
    uploadImage: 'Enviar imagem',
    chooseFromLibrary: 'Escolher da biblioteca',
    loadingLibrary: 'Carregando materiais',
    noTemplates: 'Nenhum template disponivel',
    templateCount: (count) => `${count} templates`,
    materialCount: (count) => `${count} materiais`,
    uploadClick: 'Clique, arraste ou cole uma imagem',
    resultReady: 'Resultado',
    waitingUpload: 'Aguardando upload',
    examples: 'Exemplos',
    refresh: 'Trocar',
    credits: (count) => `${count} creditos`,
    invalidImage: 'Use uma imagem PNG, JPEG ou WEBP.',
    imageTooLarge: 'A imagem deve ter no maximo 10 MB.',
    uploadPrepareError: 'Nao foi possivel preparar o envio.',
    uploadFailed: 'Falha ao enviar a imagem.',
    imageSaveError: 'Nao foi possivel salvar a imagem.',
    statusLoadError: 'Nao foi possivel carregar o status.',
    generationStartError: 'Nao foi possivel iniciar a geracao.',
    missingJobError: 'A resposta da geracao nao trouxe um id de tarefa.',
    queued: 'Na fila',
    generating: 'Gerando',
  },
  en: {
    taskFlow: 'Flow',
    generateNow: 'Generate now',
    uploadImage: 'Upload image',
    chooseFromLibrary: 'Choose from library',
    loadingLibrary: 'Loading materials',
    noTemplates: 'No templates yet',
    templateCount: (count) => `${count} templates`,
    materialCount: (count) => `${count} materials`,
    uploadClick: 'Click, drag, or paste an image',
    resultReady: 'Result',
    waitingUpload: 'Waiting for upload',
    examples: 'Examples',
    refresh: 'Refresh',
    credits: (count) => `${count} credits`,
    invalidImage: 'Use a PNG, JPEG, or WEBP image.',
    imageTooLarge: 'Image must be 10 MB or smaller.',
    uploadPrepareError: 'Upload could not be prepared.',
    uploadFailed: 'Image upload failed.',
    imageSaveError: 'Image could not be saved.',
    statusLoadError: 'Status could not be loaded.',
    generationStartError: 'Generation could not be started.',
    missingJobError: 'Generation response did not include a job id.',
    queued: 'Queued',
    generating: 'Generating',
  },
  zh: {
    taskFlow: '任务流',
    generateNow: '立即生成',
    uploadImage: '上传图片',
    chooseFromLibrary: '从素材库选择',
    loadingLibrary: '加载素材中',
    noTemplates: '暂无模板素材',
    templateCount: (count) => `${count} 个模板`,
    materialCount: (count) => `${count} 个素材`,
    uploadClick: '点击/拖拽/粘贴上传图片',
    resultReady: '生成结果',
    waitingUpload: '等待上传',
    examples: '示例商品',
    refresh: '换一换',
    credits: (count) => `${count}算力值`,
    invalidImage: '请使用 PNG、JPEG 或 WEBP 图片。',
    imageTooLarge: '图片大小不能超过 10MB。',
    uploadPrepareError: '上传准备失败。',
    uploadFailed: '图片上传失败。',
    imageSaveError: '图片保存失败。',
    statusLoadError: '状态加载失败。',
    generationStartError: '生成任务启动失败。',
    missingJobError: '生成响应缺少任务 ID。',
    queued: '排队中',
    generating: '生成中',
  },
};

export const bannerCopy: Record<DashboardLocale, { title: string }> = {
  pt: { title: 'Comece facil' },
  en: { title: 'Easy start' },
  zh: { title: '轻松上手' },
};

export const imageVideoWorkbenchCopy = {
  pt: {
    quickEdit: 'Criacao rapida',
    videoTab: 'Video de produto',
    referenceVideo: 'Referencia criativa',
    referenceHint: 'Alta fidelidade do produto, otimo para criativos em escala',
    promptPlaceholder:
      'Descreva o movimento, por exemplo: produto em destaque, camera lenta, luz natural, fundo brasileiro.',
    promptActions: ['Produto', 'Modelo', 'Material', '@'],
    promptActionSnippets: [
      'produto em destaque com camera lenta',
      'modelo segurando o produto de forma natural',
      'textura e material com brilho realista',
      'use a referencia principal como guia visual',
    ],
    promptPresets: [
      'Camera aproxima lentamente, luz premium e produto sempre no centro.',
      'Cena lifestyle com movimento natural, fundo brasileiro e profundidade suave.',
      'Camera orbitando o produto, reflexos limpos e acabamento comercial.',
    ],
    recommended: 'Sug.',
    uploadTitle: 'Imagem do produto',
    uploadHint: 'PNG/JPEG/WEBP, ate 10 MB',
    uploadDropHint: 'Envie a imagem principal do produto ou uma referencia de modelo',
    specs: 'Formato',
    specsLabel: 'Formato:',
    seconds: 's',
    standardQuality: 'Qualidade padrao',
    audioSync: 'Audio sincronizado',
    inspiration: 'Sem ideias? Use um template da biblioteca',
    canvasTitle: 'Transforme imagens em videos para vender melhor',
    canvasSubtitle: 'Geracao de video para produtos',
    canvasNotice: 'Use fotos sem rosto quando quiser aprovacao mais rapida.',
    detailLabel: 'Detalhes do produto',
    previewTitle: 'Previa do video',
    previewDescription: 'Depois da geracao, o video aparece aqui.',
    selectSourceImage: 'Selecione uma imagem de origem.',
    promptRequired: 'Digite uma descricao para gerar.',
    uploadingImage: 'Enviando imagem',
    startingGeneration: 'Iniciando geracao',
  },
  en: {
    quickEdit: 'Quick create',
    videoTab: 'Product video',
    referenceVideo: 'Creative reference',
    referenceHint: 'High product fidelity, efficient creative replication',
    promptPlaceholder:
      'Describe motion, for example: hero product shot, slow camera, natural light, Brazilian backdrop.',
    promptActions: ['Product', 'Model', 'Material', '@'],
    promptActionSnippets: [
      'hero product shot with a slow camera move',
      'model holds the product naturally',
      'realistic material texture and clean highlights',
      'use the main reference as visual guidance',
    ],
    promptPresets: [
      'Slow cinematic push-in, subtle parallax, premium product lighting.',
      'Handheld lifestyle motion, warm light, natural depth of field.',
      'Orbit camera move, glossy highlights, clean commercial finish.',
    ],
    recommended: 'Rec.',
    uploadTitle: 'Product image',
    uploadHint: 'PNG/JPEG/WEBP, up to 10 MB',
    uploadDropHint: 'Upload the product hero image or a model reference',
    specs: 'Specs',
    specsLabel: 'Specs:',
    seconds: 's',
    standardQuality: 'Standard quality',
    audioSync: 'Audio sync',
    inspiration: 'Need ideas? Start from a library template',
    canvasTitle: 'Turn product images into videos that move',
    canvasSubtitle: 'Product video generation',
    canvasNotice: 'Use images without faces when you want faster review.',
    detailLabel: 'Product detail',
    previewTitle: 'Video preview',
    previewDescription: 'After generation, the video appears here.',
    selectSourceImage: 'Select a source image.',
    promptRequired: 'Prompt is required.',
    uploadingImage: 'Uploading image',
    startingGeneration: 'Starting generation',
  },
  zh: {
    quickEdit: '快捷创作',
    videoTab: '商品视频',
    referenceVideo: '创意参考',
    referenceHint: '商品高保真，跑量创意高效复刻',
    promptPlaceholder:
      '使用 @快速调用参考内容，例如：@模特手持 @商品进行3秒的口播讲解，语气自然，画面干净。',
    promptActions: ['出镜商品', '出镜模特', '参考素材', '@'],
    promptActionSnippets: [
      '商品居中展示，镜头缓慢推进',
      '模特自然手持商品，轻微互动',
      '强调材质纹理和真实高光',
      '参考主图构图和主体比例',
    ],
    promptPresets: [
      '镜头缓慢推进，商品始终居中，光线干净有质感。',
      '生活方式场景，自然手持展示，背景贴近巴西市场。',
      '环绕镜头展示商品细节，反光干净，商业成片质感。',
    ],
    recommended: '推荐',
    uploadTitle: '上传商品图',
    uploadHint: '支持 PNG/JPEG/WEBP，最大 10MB',
    uploadDropHint: '上传商品主图或模特参考图',
    specs: '规格',
    specsLabel: '规格：',
    seconds: '秒',
    standardQuality: '标准质量',
    audioSync: '音画同步',
    inspiration: '没灵感？为您推荐优质创意，点击一键做同款',
    canvasTitle: '上传图片秒变视频，让你的商品动起来',
    canvasSubtitle: '商品视频生成',
    canvasNotice: '建议上传无人脸素材，便于更快通过审核。',
    detailLabel: '款式细节',
    previewTitle: '视频预览',
    previewDescription: '上传商品图片并生成后，视频会显示在这里。',
    selectSourceImage: '请选择一张源图片。',
    promptRequired: '请输入生成描述。',
    uploadingImage: '上传图片中',
    startingGeneration: '启动生成中',
  },
} satisfies Record<DashboardLocale, Record<string, unknown>>;

export const apparelWorkbenchCopy = {
  pt: {
    productLayout: 'Produto e composicao',
    productEmpty: 'Envie uma imagem para comecar',
    productHint: 'Use a imagem principal do produto ou uma foto de referencia',
    size: 'Tamanho',
    inspiration: 'Direcao criativa',
    quick: 'Criacao rapida',
    hot: 'HOT',
    advanced: 'Avancado',
    promptPlaceholder: 'Descreva o fundo ou escolha um template da biblioteca',
    promptIdeas: 'Sugestoes de descricao:',
    addFromTemplate: 'Adicionar da biblioteca',
    promptIdeaGroups: [
      {
        category: 'Vitrine',
        prompts: [
          'vitrine clean com pedestal claro e sombra suave',
          'composicao premium de loja com fundo neutro',
        ],
      },
      {
        category: 'Natureza',
        prompts: [
          'luz natural, plantas tropicais e textura organica',
          'fundo de praia brasileira com cor suave e produto nitido',
        ],
      },
      {
        category: 'Datas',
        prompts: [
          'campanha de presente com decoracao festiva elegante',
          'mesa sazonal brasileira com cores comerciais',
        ],
      },
      {
        category: 'Arquitetura',
        prompts: [
          'fachada moderna com linhas limpas e luz editorial',
          'interior minimalista com profundidade e reflexos suaves',
        ],
      },
      {
        category: 'Abstrato',
        prompts: [
          'formas geometricas suaves, gradiente limpo e foco no produto',
          'cenario conceitual com sombra macia e cores premium',
        ],
      },
    ],
    library: 'Biblioteca',
    templateMaterials: 'Templates',
    libraryMaterials: 'Materiais',
    settings: 'Configuracoes de criacao',
    modelType: 'Tipo de modelo',
    modelTypes: ['Modelo de moda', 'Sem modelo', 'Corpo parcial', 'Talento lifestyle'],
    scene: 'Cena',
    sceneOptions: ['Estudio minimalista', 'Editorial urbano', 'Boutique premium', 'Luz natural suave'],
    style: 'Estilo',
    stylePresets: ['Comercial limpo', 'Alta moda', 'Catalogo coreano', 'Anuncio social premium'],
    strength: 'Forca criativa',
    variants: 'Quantidade',
    negative: 'Prompt negativo',
    defaultPrompt: 'Preserve os detalhes do produto e melhore caimento, luz e apelo comercial.',
    defaultNegativePrompt: 'logo distorcido, mangas extras, maos quebradas, baixa resolucao',
    canvasTitle: 'Envie uma imagem para criar',
    banner: 'Veja como deixar a imagem mais brasileira e comercial',
    resultTitle: 'Resultado',
    resultDescription: 'A imagem gerada aparece aqui.',
    uploadRequired: 'Envie uma imagem de produto.',
    uploadingImage: 'Enviando imagem',
    startingGeneration: 'Iniciando geracao',
  },
  en: {
    productLayout: 'Product and composition',
    productEmpty: 'Upload an image to start',
    productHint: 'Use a product hero image or reference photo',
    size: 'Size',
    inspiration: 'Creative direction',
    quick: 'Quick create',
    hot: 'HOT',
    advanced: 'Advanced',
    promptPlaceholder: 'Describe the background or choose from the template library',
    promptIdeas: 'Description ideas:',
    addFromTemplate: 'Add from library',
    promptIdeaGroups: [
      {
        category: 'Showcase',
        prompts: [
          'clean showcase with a light pedestal and soft shadow',
          'premium retail composition with a neutral backdrop',
        ],
      },
      {
        category: 'Nature',
        prompts: [
          'natural light, tropical plants, and organic texture',
          'Brazilian beach backdrop with soft color and crisp product detail',
        ],
      },
      {
        category: 'Seasonal',
        prompts: [
          'gift campaign scene with elegant festive styling',
          'Brazilian seasonal table scene with commercial colors',
        ],
      },
      {
        category: 'Architecture',
        prompts: [
          'modern facade with clean lines and editorial lighting',
          'minimal interior with depth and soft reflections',
        ],
      },
      {
        category: 'Abstract',
        prompts: [
          'soft geometric forms, clean gradient, product-first composition',
          'conceptual set with soft shadow and premium colors',
        ],
      },
    ],
    library: 'Library',
    templateMaterials: 'Templates',
    libraryMaterials: 'Materials',
    settings: 'Creation settings',
    modelType: 'Model type',
    modelTypes: ['Fashion model', 'No model', 'Partial body', 'Lifestyle talent'],
    scene: 'Scene',
    sceneOptions: ['Minimal studio', 'Street editorial', 'Luxury boutique', 'Soft daylight'],
    style: 'Style',
    stylePresets: ['Clean commercial', 'High fashion', 'Korean catalog', 'Premium social ad'],
    strength: 'Creative strength',
    variants: 'Quantity',
    negative: 'Negative prompt',
    defaultPrompt: 'Preserve product details and improve drape, lighting, and merchandising appeal.',
    defaultNegativePrompt: 'distorted logo, extra sleeves, broken hands, low resolution',
    canvasTitle: 'Upload an image to start',
    banner: 'See how to make product images more commercial',
    resultTitle: 'Result',
    resultDescription: 'The generated product image appears here.',
    uploadRequired: 'Upload a product image.',
    uploadingImage: 'Uploading product image',
    startingGeneration: 'Starting generation',
  },
  zh: {
    productLayout: '商品及构图',
    productEmpty: '从右侧上传图片后开始制作',
    productHint: '也可以从素材库选择历史商品图',
    size: '生成尺寸',
    inspiration: '创意灵感',
    quick: '快捷创作',
    hot: 'HOT',
    advanced: '高级创作',
    promptPlaceholder: '自由输入背景描述，或从模板库中选择',
    promptIdeas: '描述词推荐：',
    addFromTemplate: '从模板库添加',
    promptIdeaGroups: [
      {
        category: '展台橱窗',
        prompts: ['干净展台橱窗，浅色底座，柔和阴影', '高端零售店陈列，背景简洁，突出商品主体'],
      },
      {
        category: '自然景观',
        prompts: ['自然光、热带绿植、真实材质纹理', '巴西海滩背景，色彩柔和，商品细节清晰'],
      },
      {
        category: '节日氛围',
        prompts: ['礼赠活动场景，节日装饰精致但不抢主体', '巴西本地节日餐桌氛围，商业色彩明亮'],
      },
      {
        category: '人文建筑',
        prompts: ['现代建筑立面，线条干净，杂志感光线', '极简室内空间，有层次和柔和反光'],
      },
      {
        category: '抽象概念',
        prompts: ['柔和几何造型，干净渐变，商品优先构图', '概念布景，柔和阴影，高级商业配色'],
      },
    ],
    library: '素材库',
    templateMaterials: '模板素材',
    libraryMaterials: '素材',
    settings: '创作设置',
    modelType: '模特类型',
    modelTypes: ['时尚模特', '无模特', '半身局部', '生活方式模特'],
    scene: '场景',
    sceneOptions: ['极简影棚', '街拍杂志', '高端精品店', '柔和自然光'],
    style: '风格',
    stylePresets: ['干净商业风', '高级时装感', '韩系目录', '高质感社媒广告'],
    strength: '创意强度',
    variants: '生成张数',
    negative: '反向提示词',
    defaultPrompt: '保留商品细节，优化垂坠、光线和商业展示质感。',
    defaultNegativePrompt: '变形 logo，多余袖子，手部异常，低清晰度',
    canvasTitle: '上传图片开始制作吧',
    banner: '看看让商品图更出彩的秘诀！',
    resultTitle: '生成结果',
    resultDescription: '商品图生成后会在这里展示。',
    uploadRequired: '请上传一张商品图。',
    uploadingImage: '上传商品图中',
    startingGeneration: '启动生成中',
  },
} satisfies Record<DashboardLocale, Record<string, unknown>>;

export const tryOnWorkbenchCopy = {
  pt: {
    uploadGarment: 'Enviar imagens',
    modelEmpty: 'Enviar modelo',
    modelHint: 'Ou escolha um modelo da biblioteca abaixo',
    garmentSingleEmpty: 'Enviar roupa',
    garmentMultiEmpty: 'Enviar varias roupas',
    garmentHint: 'Clique, arraste ou cole imagens',
    mode: 'Modo de prova',
    modeOptions: { single: 'Look unico', multi: 'Look multiplo' },
    chooseModel: 'Escolher modelo',
    officialModel: 'Biblioteca de modelos',
    customModel: 'Modelo proprio',
    noOfficialModels: 'Nenhum modelo da biblioteca disponivel. Envie um modelo proprio para continuar.',
    featureAdjust: 'Ajustes',
    pose: 'Pose',
    poseOptions: { auto: 'Pose automatica', front: 'Frente', editorial: 'Editorial', runway: 'Passarela' },
    background: 'Fundo',
    backgroundOptions: { studio: 'Estudio', street: 'Rua', minimal: 'Minimalista', boutique: 'Boutique' },
    fit: 'Caimento',
    fitOptions: { natural: 'Natural', tailored: 'Ajustado', relaxed: 'Solto' },
    description: 'Descricao da prova',
    promptPlaceholder: 'Ex.: luz editorial, preservar cores da roupa, tecido realista, postura natural.',
    preserveIdentity: 'Preservar identidade',
    library: 'Biblioteca',
    noTemplates: 'Nenhum template disponivel',
    canvasTitle: 'Envie roupas e comece a prova virtual',
    banner: 'Veja como deixar a prova de roupa mais natural',
    modelCanvasEmpty: 'Enviar modelo local',
    modelCanvasHint: 'Clique, arraste ou cole, ou escolha um modelo da biblioteca',
    garmentCanvasEmpty: 'Enviar roupa local',
    resultTitle: 'Resultado da prova',
    resultDescription: 'A imagem gerada aparece aqui.',
    garmentCount: (count: number) => `${count} imagens de roupa`,
    uploadImage: 'Enviar imagem',
    selectModelError: 'Selecione uma imagem de modelo ou um modelo da biblioteca.',
    selectSingleGarmentError: 'Selecione uma imagem de roupa.',
    selectMultiGarmentError: 'O modo multiplo precisa de pelo menos duas imagens de roupa.',
    uploadingModel: 'Enviando modelo',
    preparingModel: 'Preparando modelo',
    uploadingGarment: (index: number) => `Enviando roupa ${index}`,
    startingTryOn: 'Iniciando prova',
  },
  en: {
    uploadGarment: 'Upload images',
    modelEmpty: 'Upload model',
    modelHint: 'Or choose a model from the library below',
    garmentSingleEmpty: 'Upload garment',
    garmentMultiEmpty: 'Upload garments',
    garmentHint: 'Click, drag, or paste images',
    mode: 'Try-on mode',
    modeOptions: { single: 'Single look', multi: 'Multi look' },
    chooseModel: 'Choose model',
    officialModel: 'Model library',
    customModel: 'Custom model',
    noOfficialModels: 'No library models are available yet. Upload a custom model to continue.',
    featureAdjust: 'Adjustments',
    pose: 'Pose',
    poseOptions: { auto: 'Auto pose', front: 'Front view', editorial: 'Editorial', runway: 'Runway' },
    background: 'Background',
    backgroundOptions: { studio: 'Studio', street: 'Street', minimal: 'Minimal', boutique: 'Boutique' },
    fit: 'Fit',
    fitOptions: { natural: 'Natural fit', tailored: 'Tailored', relaxed: 'Relaxed' },
    description: 'Try-on description',
    promptPlaceholder: 'Example: editorial lighting, keep garment colors, realistic drape, natural pose.',
    preserveIdentity: 'Preserve identity',
    library: 'Library',
    noTemplates: 'No templates yet',
    canvasTitle: 'Upload apparel images to start',
    banner: 'See how to make try-on images more natural',
    modelCanvasEmpty: 'Upload local model',
    modelCanvasHint: 'Click, drag, paste, or choose a model from the library',
    garmentCanvasEmpty: 'Upload local garment',
    resultTitle: 'Try-on result',
    resultDescription: 'The generated try-on image appears here.',
    garmentCount: (count: number) => `${count} garment images`,
    uploadImage: 'Upload image',
    selectModelError: 'Select a model image or a library model.',
    selectSingleGarmentError: 'Select one garment image.',
    selectMultiGarmentError: 'Multi look needs at least two garment images.',
    uploadingModel: 'Uploading model',
    preparingModel: 'Preparing model',
    uploadingGarment: (index: number) => `Uploading garment ${index}`,
    startingTryOn: 'Starting try-on',
  },
  zh: {
    uploadGarment: '上传服饰图',
    modelEmpty: '上传模特图片',
    modelHint: '也可以在下方选择模特库',
    garmentSingleEmpty: '上传服饰图片',
    garmentMultiEmpty: '上传多件服饰图片',
    garmentHint: '支持点击/拖拽/粘贴，批量上传',
    mode: '试衣模式',
    modeOptions: { single: '单件试衣', multi: '多件试衣' },
    chooseModel: '选择模特',
    officialModel: '模特库',
    customModel: '自定义模特',
    noOfficialModels: '暂无可用模特，请上传自定义模特图继续。',
    featureAdjust: '特征调整',
    pose: '姿态',
    poseOptions: { auto: '自动姿态', front: '正面视角', editorial: '杂志姿态', runway: '走秀姿态' },
    background: '背景',
    backgroundOptions: { studio: '影棚', street: '街拍', minimal: '极简', boutique: '精品店' },
    fit: '版型',
    fitOptions: { natural: '自然合身', tailored: '修身', relaxed: '宽松' },
    description: '试衣描述',
    promptPlaceholder: '例如：高级杂志光效，保留服饰颜色，真实褶皱，自然站姿。',
    preserveIdentity: '保留人物身份',
    library: '素材库',
    noTemplates: '暂无模板素材',
    canvasTitle: '上传服饰类图片，开始制作吧',
    banner: '看看让服饰图更出彩的秘诀！',
    modelCanvasEmpty: '从本地上传模特图',
    modelCanvasHint: '点击/拖拽/粘贴，或从模特库中选择',
    garmentCanvasEmpty: '从本地上传服饰图',
    resultTitle: '试衣结果',
    resultDescription: '生成后的试衣图会在这里展示。',
    garmentCount: (count: number) => `${count} 张服饰图`,
    uploadImage: '上传图片',
    selectModelError: '请选择模特图片或模特库中的模特。',
    selectSingleGarmentError: '请选择一张服饰图。',
    selectMultiGarmentError: '多件试衣至少需要两张服饰图。',
    uploadingModel: '上传模特中',
    preparingModel: '准备模特中',
    uploadingGarment: (index: number) => `上传服饰 ${index}`,
    startingTryOn: '启动试衣中',
  },
} satisfies Record<DashboardLocale, Record<string, unknown>>;
