import type { DashboardLocale } from '@/lib/dashboard/content';

type CommonWorkbenchCopy = {
  taskFlow: string;
  generateNow: string;
  uploadImage: string;
  chooseFromLibrary: string;
  loadingLibrary: string;
  noTemplates: string;
  templateCount: (count: number) => string;
  materialCount: (count: number) => string;
  uploadClick: string;
  resultReady: string;
  waitingUpload: string;
  examples: string;
  refresh: string;
  credits: (count: number) => string;
  invalidImage: string;
  imageTooLarge: string;
  uploadPrepareError: string;
  uploadFailed: string;
  imageSaveError: string;
  statusLoadError: string;
  generationStartError: string;
  missingJobError: string;
  queued: string;
  generating: string;
};

export const commonWorkbenchCopy: Record<DashboardLocale, CommonWorkbenchCopy> = {
  pt: {
    taskFlow: 'Fluxo',
    generateNow: 'Gerar agora',
    uploadImage: 'Enviar imagem',
    chooseFromLibrary: 'Escolher do histórico',
    loadingLibrary: 'Carregando materiais',
    noTemplates: 'Nenhum template disponível',
    templateCount: (count) => `${count} templates`,
    materialCount: (count) => `${count} materiais`,
    uploadClick: 'Clique, arraste ou cole uma imagem',
    resultReady: 'Resultado',
    waitingUpload: 'Aguardando upload',
    examples: 'Exemplos',
    refresh: 'Trocar',
    credits: (count) => `${count} créditos`,
    invalidImage: 'Use uma imagem PNG, JPEG ou WEBP.',
    imageTooLarge: 'A imagem deve ter no máximo 10 MB.',
    uploadPrepareError: 'Não foi possível preparar o envio.',
    uploadFailed: 'Falha ao enviar o material.',
    imageSaveError: 'Não foi possível salvar o material.',
    statusLoadError: 'Não foi possível carregar o status.',
    generationStartError: 'Não foi possível iniciar a geração.',
    missingJobError: 'A resposta da geração veio incompleta.',
    queued: 'Na fila',
    generating: 'Gerando',
  },
  en: {
    taskFlow: 'Flow',
    generateNow: 'Generate now',
    uploadImage: 'Upload image',
    chooseFromLibrary: 'Choose from history',
    loadingLibrary: 'Loading materials',
    noTemplates: 'No templates yet',
    templateCount: (count) => `${count} templates`,
    materialCount: (count) => `${count} materials`,
    uploadClick: 'Click, drag, or paste an image',
    resultReady: 'Result',
    waitingUpload: 'Waiting for upload',
    examples: 'Examples',
    refresh: 'Refresh',
    credits: (count) => `${count} credits`,
    invalidImage: 'Use a PNG, JPEG, or WEBP image.',
    imageTooLarge: 'Image must be 10 MB or smaller.',
    uploadPrepareError: 'Upload could not be prepared.',
    uploadFailed: 'Asset upload failed.',
    imageSaveError: 'Asset could not be saved.',
    statusLoadError: 'Status could not be loaded.',
    generationStartError: 'Generation could not be started.',
    missingJobError: 'Generation response was incomplete.',
    queued: 'Queued',
    generating: 'Generating',
  },
  zh: {
    taskFlow: '任务流',
    generateNow: '立即生成',
    uploadImage: '上传图片',
    chooseFromLibrary: '从历史选择',
    loadingLibrary: '加载素材中',
    noTemplates: '暂无模板素材',
    templateCount: (count) => `${count} 个模板`,
    materialCount: (count) => `${count} 个素材`,
    uploadClick: '点击/拖拽/粘贴上传图片',
    resultReady: '生成结果',
    waitingUpload: '等待上传',
    examples: '示例商品',
    refresh: '换一换',
    credits: (count) => `${count} 算力值`,
    invalidImage: '请使用 PNG、JPEG 或 WEBP 图片。',
    imageTooLarge: '图片大小不能超过 10MB。',
    uploadPrepareError: '上传准备失败。',
    uploadFailed: '素材上传失败。',
    imageSaveError: '素材保存失败。',
    statusLoadError: '状态加载失败。',
    generationStartError: '生成任务启动失败。',
    missingJobError: '生成响应异常，请重试。',
    queued: '排队中',
    generating: '生成中',
  },
};

export const bannerCopy: Record<DashboardLocale, { title: string }> = {
  pt: { title: 'Comece fácil' },
  en: { title: 'Easy start' },
  zh: { title: '轻松上手' },
};

export const imageVideoWorkbenchCopy = {
  pt: {
    quickEdit: 'Criação rápida',
    videoTab: 'Vídeo de produto',
    referenceVideo: 'Referência criativa',
    referenceHint: 'Alta fidelidade do produto, ótimo para criativos em escala',
    durationLabel: 'Duração',
    durationValue: (seconds: number) => `${seconds}s`,
    promptPlaceholder:
      'Descreva o movimento, por exemplo: produto em destaque, camera lenta, luz natural, fundo brasileiro.',
    promptPresets: [
      'Câmera aproxima lentamente, luz premium e produto sempre no centro.',
      'Cena lifestyle com movimento natural, fundo brasileiro e profundidade suave.',
      'Câmera orbitando o produto, reflexos limpos e acabamento comercial.',
    ],
    modelModes: {
      wanxiang_2_7: {
        eyebrow: 'Modelo 1',
        title: 'Imagem para vídeo Pro',
        description: 'Modelo mais poderoso',
      },
      wanxiang_2_6_first_frame: {
        eyebrow: 'Modelo 2',
        title: 'Imagem para vídeo',
        description: 'Baseado no primeiro frame',
      },
    },
    materialAction: 'Material de referencia',
    appearingModelAction: 'Modelo em cena',
    modelLibraryTitle: 'Adicionar modelo em cena',
    modelGenderFilter: 'Sexo',
    modelStyleFilter: 'Estilo',
    modelAgeFilter: 'Idade',
    modelAgeOptions: {
      all: 'Todos',
      child: 'Criança',
      youth: 'Jovem',
      middle: 'Adulto',
      senior: 'Sênior',
    },
    modelGenderOptions: {
      all: 'Todos',
      female: 'Mulher',
      male: 'Homem',
    },
    loadingModels: 'Carregando modelos',
    modelLibraryError: 'Não foi possível carregar os modelos.',
    retryModels: 'Tentar novamente',
    noFilteredModels: 'Nenhum modelo neste filtro.',
    selectedAppearingModel: 'Modelo selecionado',
    removeAppearingModel: 'Remover modelo',
    appearingModelPromptPrefix: (name: string) => `Modelo em cena: ${name}.`,
    referencePanelTitle: 'Adicionar materiais de referência',
    close: 'Fechar',
    uploadReferenceImage: 'Enviar imagem',
    referenceDimensionHint: (min: number, max: number) =>
      `Imagem: ${min}-${max}px em cada lado.`,
    referenceMaterialCount: (count: number) => `${count} imagem selecionada`,
    selectedReferenceImage: 'Imagem selecionada',
    selectedReferenceImageReady: 'Imagem pronta',
    removeReferenceImage: 'Remover imagem',
    referenceImageLimit: 'Envie apenas uma imagem principal por vez.',
    invalidReference: 'Use imagem PNG, JPEG ou WEBP.',
    referenceTooLarge: 'Cada material deve ter no máximo 10 MB.',
    referenceDimensionInvalid: (
      width: number,
      height: number,
      min: number,
      max: number
    ) =>
      `Esta imagem tem ${width} x ${height}px. Use uma imagem entre ${min} e ${max}px em cada lado.`,
    specs: 'Formato',
    specsLabel: 'Formato:',
    inspiration: 'Sem ideias? Use um template da biblioteca',
    previewTemplate: 'Prévia',
    templateDetailTitle: 'Detalhes do template',
    templateTitle: 'Título do vídeo',
    templateCategory: 'Categoria do produto',
    templatePrompt: 'Descrição do vídeo',
    useTemplate: 'Usar este template',
    canvasTitle: 'Transforme imagens em vídeos para vender melhor',
    canvasSubtitle: 'Geração de vídeo para produtos',
    detailLabel: 'Detalhes do produto',
    emptyMaterialStyle: 'Detalhes do look',
    emptyMaterialScene: 'Cenário de uso',
    emptyMaterialTexture: 'Textura de tecido',
    previewTitle: 'Prévia do vídeo',
    previewDescription: 'Depois da geração, o vídeo aparece aqui.',
    selectSourceImage: 'Envie pelo menos uma imagem nos materiais de referencia.',
    promptRequired: 'Digite uma descrição para gerar.',
    uploadingImage: 'Enviando imagens',
    startingGeneration: 'Iniciando geração',
  },
  en: {
    quickEdit: 'Quick create',
    videoTab: 'Product video',
    referenceVideo: 'Creative reference',
    referenceHint: 'High product fidelity, efficient creative replication',
    durationLabel: 'Duration',
    durationValue: (seconds: number) => `${seconds}s`,
    promptPlaceholder:
      'Describe motion, for example: hero product shot, slow camera, natural light, Brazilian backdrop.',
    promptPresets: [
      'Slow cinematic push-in, subtle parallax, premium product lighting.',
      'Handheld lifestyle motion, warm light, natural depth of field.',
      'Orbit camera move, glossy highlights, clean commercial finish.',
    ],
    modelModes: {
      wanxiang_2_7: {
        eyebrow: 'Model 1',
        title: 'Image-to-video Pro',
        description: 'Most powerful model',
      },
      wanxiang_2_6_first_frame: {
        eyebrow: 'Model 2',
        title: 'Image-to-video',
        description: 'Based on first frame',
      },
    },
    materialAction: 'Reference materials',
    appearingModelAction: 'Model in scene',
    modelLibraryTitle: 'Add model in scene',
    modelGenderFilter: 'Gender',
    modelStyleFilter: 'Style',
    modelAgeFilter: 'Age',
    modelAgeOptions: {
      all: 'Any',
      child: 'Child',
      youth: 'Youth',
      middle: 'Adult',
      senior: 'Senior',
    },
    modelGenderOptions: {
      all: 'Any',
      female: 'Female',
      male: 'Male',
    },
    loadingModels: 'Loading models',
    modelLibraryError: 'Models could not be loaded.',
    retryModels: 'Retry',
    noFilteredModels: 'No models match this filter.',
    selectedAppearingModel: 'Selected model',
    removeAppearingModel: 'Remove model',
    appearingModelPromptPrefix: (name: string) => `Model in scene: ${name}.`,
    referencePanelTitle: 'Add reference materials',
    close: 'Close',
    uploadReferenceImage: 'Upload image',
    referenceDimensionHint: (min: number, max: number) =>
      `Image size: ${min}-${max}px on each side.`,
    referenceMaterialCount: (count: number) => `${count} image selected`,
    selectedReferenceImage: 'Selected image',
    selectedReferenceImageReady: 'Image ready',
    removeReferenceImage: 'Remove image',
    referenceImageLimit: 'Upload one main image at a time.',
    invalidReference: 'Use a PNG, JPEG, or WEBP image.',
    referenceTooLarge: 'Each reference asset must be 10 MB or smaller.',
    referenceDimensionInvalid: (
      width: number,
      height: number,
      min: number,
      max: number
    ) =>
      `This image is ${width} x ${height}px. Use an image between ${min} and ${max}px on each side.`,
    specs: 'Specs',
    specsLabel: 'Specs:',
    inspiration: 'Need ideas? Start from a library template',
    previewTemplate: 'Preview',
    templateDetailTitle: 'Template details',
    templateTitle: 'Video title',
    templateCategory: 'Product category',
    templatePrompt: 'Video description',
    useTemplate: 'Use this template',
    canvasTitle: 'Turn product images into videos that move',
    canvasSubtitle: 'Product video generation',
    detailLabel: 'Product detail',
    emptyMaterialStyle: 'Style detail',
    emptyMaterialScene: 'Scene detail',
    emptyMaterialTexture: 'Fabric texture',
    previewTitle: 'Video preview',
    previewDescription: 'After generation, the video appears here.',
    selectSourceImage: 'Upload at least one image in reference materials.',
    promptRequired: 'Prompt is required.',
    uploadingImage: 'Uploading images',
    startingGeneration: 'Starting generation',
  },
  zh: {
    quickEdit: '快捷创作',
    videoTab: '商品视频',
    referenceVideo: '创意参考',
    referenceHint: '商品高还原，爆款创意高效复刻',
    durationLabel: '视频时长',
    durationValue: (seconds: number) => `${seconds}秒`,
    promptPlaceholder:
      '例如：商品缓慢旋转展示细节，镜头稳定，颜色、材质和图案保持一致。',
    promptPresets: [
      '镜头缓慢推进，商品始终居中，光线干净有质感。',
      '生活方式场景，自然手持展示，背景贴近巴西市场。',
      '环绕镜头展示商品细节，反光干净，商业成片质感。',
    ],
    modelModes: {
      wanxiang_2_7: {
        eyebrow: '模型1',
        title: '图生视频 Pro',
        description: '最强模型',
      },
      wanxiang_2_6_first_frame: {
        eyebrow: '模型2',
        title: '图生视频',
        description: '基于首帧',
      },
    },
    materialAction: '参考素材',
    appearingModelAction: '出镜模特',
    modelLibraryTitle: '添加出镜模特',
    modelGenderFilter: '性别',
    modelStyleFilter: '风格',
    modelAgeFilter: '年龄',
    modelAgeOptions: {
      all: '不限',
      child: '儿童',
      youth: '青年',
      middle: '中年',
      senior: '老年',
    },
    modelGenderOptions: {
      all: '不限',
      female: '女',
      male: '男',
    },
    loadingModels: '加载模特中',
    modelLibraryError: '模特库加载失败。',
    retryModels: '重试',
    noFilteredModels: '当前筛选暂无模特。',
    selectedAppearingModel: '已选择出镜模特',
    removeAppearingModel: '移除出镜模特',
    appearingModelPromptPrefix: (name: string) => `出镜模特：${name}。`,
    referencePanelTitle: '添加参考素材',
    close: '关闭',
    uploadReferenceImage: '上传图片',
    referenceDimensionHint: (min: number, max: number) =>
      `图片尺寸：宽高每边 ${min}-${max}px。`,
    referenceMaterialCount: (count: number) => `已选择 ${count} 张图片`,
    selectedReferenceImage: '已选择图片',
    selectedReferenceImageReady: '图片已就绪',
    removeReferenceImage: '移除图片',
    referenceImageLimit: '图片一次只能选择 1 张。',
    invalidReference: '请上传 PNG、JPEG 或 WEBP 图片。',
    referenceTooLarge: '单个参考素材不能超过 10MB。',
    referenceDimensionInvalid: (
      width: number,
      height: number,
      min: number,
      max: number
    ) =>
      `这张图片是 ${width} x ${height}px。请上传宽高每边 ${min}-${max}px 的图片。`,
    specs: '规格',
    specsLabel: '规格：',
    inspiration: '没灵感？为您推荐优质创意，点击一键做同款',
    previewTemplate: '预览',
    templateDetailTitle: '模板详情',
    templateTitle: '视频标题',
    templateCategory: '商品类目',
    templatePrompt: '视频描述',
    useTemplate: '使用此模板',
    canvasTitle: '上传图片秒变视频，让你的商品动起来',
    canvasSubtitle: '商品视频生成',
    detailLabel: '款式细节',
    emptyMaterialStyle: '款式细节',
    emptyMaterialScene: '场景细节',
    emptyMaterialTexture: '面料质感',
    previewTitle: '视频预览',
    previewDescription: '在参考素材中上传图片并生成后，视频会显示在这里。',
    selectSourceImage: '请先在参考素材中上传至少一张图片。',
    promptRequired: '请输入生成描述。',
    uploadingImage: '上传图片中',
    startingGeneration: '正在启动生成',
  },
} satisfies Record<DashboardLocale, Record<string, unknown>>;

export const apparelWorkbenchCopy = {
  pt: {
    productLayout: 'Produto e composição',
    productEmpty: 'Envie uma imagem para começar',
    productHint: 'Use a imagem principal do produto ou uma foto de referência',
    size: 'Tamanho',
    inspiration: 'Direção criativa',
    quick: 'Criação rápida',
    hot: 'HOT',
    advanced: 'Avançado',
    promptPlaceholder: 'Descreva o fundo ou escolha um template da biblioteca',
    promptIdeas: 'Sugestões de descrição:',
    addFromTemplate: 'Adicionar da biblioteca',
    promptIdeaGroups: [
      {
        category: 'Vitrine',
        prompts: [
          'vitrine clean com pedestal claro e sombra suave',
          'composição premium de loja com fundo neutro',
        ],
      },
      {
        category: 'Natureza',
        prompts: [
          'luz natural, plantas tropicais e textura orgânica',
          'fundo de praia brasileira com cor suave e produto nitido',
        ],
      },
      {
        category: 'Datas',
        prompts: [
          'campanha de presente com decoração festiva elegante',
          'mesa sazonal brasileira com cores comerciais',
        ],
      },
      {
        category: 'Arquitetura',
        prompts: [
          'fachada moderna com linhas limpas e luz editorial',
          'interior minimalista com profundidade e reflexos suaves',
        ],
      },
      {
        category: 'Abstrato',
        prompts: [
          'formas geométricas suaves, gradiente limpo e foco no produto',
          'cenário conceitual com sombra macia e cores premium',
        ],
      },
    ],
    library: 'Histórico',
    templateMaterials: 'Templates',
    libraryMaterials: 'Histórico',
    defaultPrompt: 'Preserve os detalhes do produto e melhore caimento, luz e apelo comercial.',
    canvasTitle: 'Envie uma imagem para criar',
    banner: 'Veja como deixar a imagem mais brasileira e comercial',
    resultTitle: 'Resultado',
    resultDescription: 'A imagem gerada aparece aqui.',
    uploadRequired: 'Envie uma imagem de produto.',
    uploadingImage: 'Enviando imagem',
    startingGeneration: 'Iniciando geração',
  },
  en: {
    productLayout: 'Product and composition',
    productEmpty: 'Upload an image to start',
    productHint: 'Use a product hero image or reference photo',
    size: 'Size',
    inspiration: 'Creative direction',
    quick: 'Quick create',
    hot: 'HOT',
    advanced: 'Advanced',
    promptPlaceholder: 'Describe the background or choose from the template library',
    promptIdeas: 'Description ideas:',
    addFromTemplate: 'Add from library',
    promptIdeaGroups: [
      {
        category: 'Showcase',
        prompts: [
          'clean showcase with a light pedestal and soft shadow',
          'premium retail composition with a neutral backdrop',
        ],
      },
      {
        category: 'Nature',
        prompts: [
          'natural light, tropical plants, and organic texture',
          'Brazilian beach backdrop with soft color and crisp product detail',
        ],
      },
      {
        category: 'Seasonal',
        prompts: [
          'gift campaign scene with elegant festive styling',
          'Brazilian seasonal table scene with commercial colors',
        ],
      },
      {
        category: 'Architecture',
        prompts: [
          'modern facade with clean lines and editorial lighting',
          'minimal interior with depth and soft reflections',
        ],
      },
      {
        category: 'Abstract',
        prompts: [
          'soft geometric forms, clean gradient, product-first composition',
          'conceptual set with soft shadow and premium colors',
        ],
      },
    ],
    library: 'History',
    templateMaterials: 'Templates',
    libraryMaterials: 'History',
    defaultPrompt: 'Preserve product details and improve drape, lighting, and merchandising appeal.',
    canvasTitle: 'Upload an image to start',
    banner: 'See how to make product images more commercial',
    resultTitle: 'Result',
    resultDescription: 'The generated product image appears here.',
    uploadRequired: 'Upload a product image.',
    uploadingImage: 'Uploading product image',
    startingGeneration: 'Starting generation',
  },
  zh: {
    productLayout: '商品及构图',
    productEmpty: '从右侧上传图片后开始制作',
    productHint: '也可以从历史素材选择商品图',
    size: '生成尺寸',
    inspiration: '创意灵感',
    quick: '快捷创作',
    hot: 'HOT',
    advanced: '高级创作',
    promptPlaceholder: '输入背景描述，或从模板库中选择',
    promptIdeas: '描述词推荐：',
    addFromTemplate: '从模板库添加',
    promptIdeaGroups: [
      {
        category: '展台橱窗',
        prompts: ['干净展台橱窗，浅色底座，柔和阴影', '高端零售店陈列，背景简洁，突出商品主体'],
      },
      {
        category: '自然景观',
        prompts: ['自然光、热带绿植、真实材质纹理', '巴西海滩背景，色彩柔和，商品细节清晰'],
      },
      {
        category: '节日氛围',
        prompts: ['礼赠活动场景，节日装饰精致但不抢主体', '巴西本地节日餐桌氛围，商业色彩明亮'],
      },
      {
        category: '人文建筑',
        prompts: ['现代建筑立面，线条干净，杂志感光线', '极简室内空间，有层次和柔和反光'],
      },
      {
        category: '抽象概念',
        prompts: ['柔和几何造型，干净渐变，商品优先构图', '概念布景，柔和阴影，高级商业配色'],
      },
    ],
    library: '历史素材',
    templateMaterials: '模板素材',
    libraryMaterials: '历史素材',
    defaultPrompt: '保留商品细节，优化垂坠、光线和商业展示质感。',
    canvasTitle: '上传图片开始制作吧',
    banner: '看看让商品图更出彩的秘诀！',
    resultTitle: '生成结果',
    resultDescription: '商品图生成后会在这里展示。',
    uploadRequired: '请上传一张商品图。',
    uploadingImage: '上传商品图中',
    startingGeneration: '正在启动生成',
  },
} satisfies Record<DashboardLocale, Record<string, unknown>>;

export const tryOnWorkbenchCopy = {
  pt: {
    uploadGarment: 'Roupa',
    garmentWorkbenchEmpty: 'Envie imagens no painel da direita para começar',
    upperGarment: 'Parte de cima',
    lowerGarment: 'Parte de baixo',
    upperGarmentEmpty: 'Enviar parte de cima',
    lowerGarmentEmpty: 'Enviar parte de baixo',
    lowerGarmentDisabled: 'Look único não usa parte de baixo',
    onePieceHint: 'Use apenas a peça principal',
    garmentHint: 'Clique, arraste ou cole imagens',
    mode: 'Modo de prova',
    modeOptions: { single: 'Look único', multi: 'Look combinado' },
    size: 'Tamanho',
    chooseModel: 'Biblioteca de modelos',
    modelAgeFilter: 'Idade',
    modelAgeOptions: {
      all: 'Todos',
      child: 'Criança',
      youth: 'Jovem',
      middle: 'Meia-idade',
      senior: 'Idoso',
    },
    modelGenderFilter: 'Gênero',
    modelGenderOptions: { all: 'Todos', female: 'Feminino', male: 'Masculino' },
    modelStyleFilter: 'Estilo',
    noOfficialModels: 'A biblioteca de modelos ainda não tem itens disponíveis.',
    noFilteredModels: 'Nenhum modelo nesta combinação.',
    modelDetailTitle: 'Detalhes do modelo',
    modelDisplayImage: 'Imagem de exibição',
    modelStyleIntro: 'Estilo e características',
    useThisModel: 'Usar este modelo',
    selectedModel: 'Selecionado',
    close: 'Fechar',
    templateMaterials: 'Templates',
    description: 'Descrição da prova',
    promptPlaceholder: 'Ex.: luz editorial, preservar cores da roupa, tecido realista, postura natural.',
    canvasTitle: 'Envie roupas e comece a prova virtual',
    banner: 'Veja como deixar a prova de roupa mais natural',
    resultTitle: 'Resultado da prova',
    resultDescription: 'A imagem gerada aparece aqui.',
    garmentCount: (count: number) => `${count} imagens de roupa`,
    uploadImage: 'Enviar imagem',
    selectModelError: 'Selecione um modelo da biblioteca.',
    selectSingleGarmentError: 'Selecione uma imagem de roupa.',
    selectMultiGarmentError: 'O look combinado precisa de parte de cima e parte de baixo.',
    preparingModel: 'Preparando modelo',
    uploadingGarment: (index: number) => `Enviando roupa ${index}`,
    startingTryOn: 'Iniciando prova',
  },
  en: {
    uploadGarment: 'Apparel',
    garmentWorkbenchEmpty: 'Upload images on the right to start',
    upperGarment: 'Upper garment',
    lowerGarment: 'Lower garment',
    upperGarmentEmpty: 'Upload upper garment',
    lowerGarmentEmpty: 'Upload lower garment',
    lowerGarmentDisabled: 'One-piece mode does not use lower garment',
    onePieceHint: 'Use the main garment only',
    garmentHint: 'Click, drag, or paste images',
    mode: 'Try-on mode',
    modeOptions: { single: 'One-piece', multi: 'Paired apparel' },
    size: 'Size',
    chooseModel: 'Model library',
    modelAgeFilter: 'Age',
    modelAgeOptions: {
      all: 'All',
      child: 'Children',
      youth: 'Youth',
      middle: 'Middle-aged',
      senior: 'Senior',
    },
    modelGenderFilter: 'Gender',
    modelGenderOptions: { all: 'All', female: 'Female', male: 'Male' },
    modelStyleFilter: 'Style',
    noOfficialModels: 'No model-library items are available yet. Models will come from the model library flow.',
    noFilteredModels: 'No models match these filters.',
    modelDetailTitle: 'Model details',
    modelDisplayImage: 'Display image',
    modelStyleIntro: 'Style and traits',
    useThisModel: 'Use this model',
    selectedModel: 'Selected',
    close: 'Close',
    templateMaterials: 'Templates',
    description: 'Try-on description',
    promptPlaceholder: 'Example: editorial lighting, keep garment colors, realistic drape, natural pose.',
    canvasTitle: 'Upload apparel images to start',
    banner: 'See how to make try-on images more natural',
    resultTitle: 'Try-on result',
    resultDescription: 'The generated try-on image appears here.',
    garmentCount: (count: number) => `${count} garment images`,
    uploadImage: 'Upload image',
    selectModelError: 'Select a model from the model library.',
    selectSingleGarmentError: 'Select one garment image.',
    selectMultiGarmentError: 'Paired apparel needs upper and lower garment images.',
    preparingModel: 'Preparing model',
    uploadingGarment: (index: number) => `Uploading garment ${index}`,
    startingTryOn: 'Starting try-on',
  },
  zh: {
    uploadGarment: '服饰',
    garmentWorkbenchEmpty: '从右侧上传图片后开始制作',
    upperGarment: '上装',
    lowerGarment: '下装',
    upperGarmentEmpty: '上传上装图片',
    lowerGarmentEmpty: '上传下装图片',
    lowerGarmentDisabled: '连体服饰不需要下装',
    onePieceHint: '只上传主服饰即可',
    garmentHint: '支持点击/拖拽/粘贴上传',
    mode: '试衣模式',
    modeOptions: { single: '连体服饰', multi: '搭配服饰' },
    size: '生成尺寸',
    chooseModel: '模特库',
    modelAgeFilter: '年龄',
    modelAgeOptions: {
      all: '全部',
      child: '儿童',
      youth: '青年',
      middle: '中年',
      senior: '老年',
    },
    modelGenderFilter: '性别',
    modelGenderOptions: { all: '全部', female: '女', male: '男' },
    modelStyleFilter: '风格',
    noOfficialModels: '暂无可用模特库素材，后续由模特库产出后可选择。',
    noFilteredModels: '当前筛选下暂无模特。',
    modelDetailTitle: '模特详情',
    modelDisplayImage: '展示图',
    modelStyleIntro: '个人风格介绍',
    useThisModel: '使用这个模特',
    selectedModel: '已选中',
    close: '关闭',
    templateMaterials: '模板素材',
    description: '试衣描述',
    promptPlaceholder: '例如：高级杂志光效，保留服饰颜色，真实褶皱，自然站姿。',
    canvasTitle: '上传服饰类图片，开始制作吧',
    banner: '看看让服饰图更出彩的秘诀！',
    resultTitle: '试衣结果',
    resultDescription: '生成后的试衣图会在这里展示。',
    garmentCount: (count: number) => `${count} 张服饰图`,
    uploadImage: '上传图片',
    selectModelError: '请先从模特库选择模特。',
    selectSingleGarmentError: '请选择一张服饰图。',
    selectMultiGarmentError: '搭配服饰需要上装和下装两张图。',
    preparingModel: '准备模特中',
    uploadingGarment: (index: number) => `上传服饰 ${index}`,
    startingTryOn: '正在启动试衣',
  },
} satisfies Record<DashboardLocale, Record<string, unknown>>;
